server: 
  port: 9025


spring:
  datasource:
    url: jdbc:postgresql://project2.cvnkugrfdj8n.us-east-2.rds.amazonaws.com:5432/storedb
    username: storeadmin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:      
      ddl-auto: create